[package]
name = "mates"
version = "0.1.0"
authors = ["Markus Unterwaditzer <markus@unterwaditzer.net>"]

[lib]
name = "mates"
path = "src/mates/lib.rs"

[[bin]]
name = "mates"
test = false
doc = false

[dependencies]
uuid = "*"
atomicwrites = "*"
email = "*"
clap = "*"

[dependencies.vobject]
git = "https://github.com/untitaker/rust-vobject.git"
