[package]
name = "mates"
version = "0.1.1"
authors = ["Markus Unterwaditzer <markus@unterwaditzer.net>"]
license = "MIT"

[lib]
name = "mates"
path = "src/mates/lib.rs"

[[bin]]
name = "mates"
test = false
doc = false

[dependencies]
uuid = "0.1"
atomicwrites = "0.0"
email = "0.0"
clap = "1"
vobject = "0.1"
