[package]
name = "mates"
version = "0.1.2"
authors = ["Markus Unterwaditzer <markus@unterwaditzer.net>"]
license = "MIT"
keywords = ["vdir", "vcard", "contacts", "addressbook"]
readme = "README.md"

description = "A very simple commandline addressbook"
documentation = "https://github.com/untitaker/mates.rs"
homepage = "https://github.com/untitaker/mates.rs"
repository = "https://github.com/untitaker/mates.rs"

[lib]
name = "mates"
path = "src/mates/lib.rs"

[[bin]]
name = "mates"
test = false
doc = false

[dependencies]
uuid = "0.1"
atomicwrites = "0.0"
email = "0.0"
clap = "2"
vobject = "0.1"
