[package]
name = "mates"
version = "0.0.1"
authors = ["Markus Unterwaditzer <markus@unterwaditzer.net>"]

[lib]
name = "mates"
path = "src/mates/lib.rs"

[[bin]]
name = "mates"
test = false
doc = false

[dependencies]
email = "0.0.7"
uuid = "*"

[dependencies.vobject]
git = "https://github.com/untitaker/rust-vobject.git"
